### ISSUE TITLE
Consider mirroring to Codeberg

### ISSUE THREAD

**Issue by throwaway-d** [Ahwxorg/pinternet#4]
See:
- https://github.com/nesaku/BiblioReads/issues/3
- https://codeberg.org/Recommendations/Mirror_to_Codeberg

**Comment by Ahwxorg** [comment]
Give me a few days and I'll mirror to git.ahwx.org. Will probably also use Codeberg in the future, I'll link to it in the README.md file.

**Comment by Ahwxorg** [comment]
[codeberg mirror](https://codeberg.org/ahwx/pinternet)

**Comment by Ahwxorg** [comment]
You are right, it was quite the hassle to keep it synced. If there is a way to automate that, I'd be glad to update the mirror again.

**Comment by Ahwxorg** [comment]
I'll look into this when I have a little more free time on my hands.
